[project]
name = "nonebot-plugin-quotation"
version = "0.1.1"
description = "Simple quotation plugin"
readme = "README.md"
keywords = ["nonebot", "nonebot2", "qqbot", "bot"]
authors = [
    { name = "MerCuJerry", email = "mercujerry@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "nonebot2>=2.5.0",
    "nonebot_plugin_localstore>=0.7.4",
    "nonebot_plugin_alconna>=0.62.0",
]
license = {file = "LICENSE"}

[project.urls]
homepage = "https://github.com/MerCuJerry/nonebot-plugin-quotation"

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
source-include = ["nonebot_plugin_quotation"]